'''
Even Fibonacci numbers
Problem 2 
'''

'''
English version
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

#Setting
a = 1
b = 0
sum = 0         
all_sum = 0     

#loop until a is over 4000000 
while a <= 4000000 :
    sum = a + b           #Before value + after value    
    b = a                 
    a = sum
    if sum%2 == 0:        #Check even-valued terms 
        all_sum += sum    #Accumulate only even-valued terms  

#answer
print(all_sum)

#time spent : 0.0 seconds








'''
Korean version
피보나치 수열의 각 항은 바로 앞의 항 두 개를 더한 것이 됩니다. 1과 2로 시작하는 경우 이 수열은 아래와 같습니다.
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
짝수이면서 4백만 이하인 모든 항을 더하면 얼마가 됩니까?
'''


#초기값 설정
a = 1
b = 0
sum = 0         
all_sum = 0     

#400만이 넘을 때까지 반복 
while a <= 4000000 :
    sum = a + b           #이전 값과 다음 값을 더해주기    
    b = a                 
    a = sum
    if sum%2 == 0:        #짝수인지 확인
        all_sum += sum    #짝수인 경우에 한해서만 값을 더해주기  

#정답
print(all_sum)

#계산에 걸린 시간 : 0.0 seconds
